print ('====DÉFI 09====')
num = int(input('Digite um número para ver sua tabuada: '))
print('~' * 13)
print(f'{num} x {1:2} = {num*1}')
print(f'{num} x {2:2} = {num*2}')
print(f'{num} x {3:2} = {num*3}')
print(f'{num} x {4:2} = {num*4}')
print(f'{num} x {5:2} = {num*5}')
print(f'{num} x {6:2} = {num*6}')
print(f'{num} x {7:2} = {num*7}')
print(f'{num} x {8:2} = {num*8}')
print(f'{num} x {9:2} = {num*9}')
print(f'{num} x {10} = {num*10}')
print(f'{num} x {11} = {num*11}')
print(f'{num} x {12} = {num*12}')
print(f'{num} x {13} = {num*13}')
print(f'{num} x {14} = {num*14}')
print(f'{num} x {15} = {num*15}')
print(f'{num} x {16} = {num*16}')
print(f'{num} x {17} = {num*17}')
print(f'{num} x {18} = {num*18}')
print(f'{num} x {19} = {num*19}')
print(f'{num} x {20} = {num*20}')
print('~' * 13)