print ('====DÉFI 04====')
a = input('Digite algo: ')
print('Segue abaixo as informações.')
print('É Primitivo?', type(a))
print('É Alfanumérico?', a.isalnum())
print('É Alfabético?', a.isalpha())
print('É Numérico?', a.isnumeric())
print('É Decimal?', a.isdecimal())
print('É somente maiúsculas?', a.isupper())
print('É somente minúsculas?', a.islower())
print('Está capitalizado?', a.istitle())